spring:
  flyway:
    url: jdbc:h2:mem:transactiondb;DB_CLOSE_DELAY=-1;
    user: sa
    locations: classpath:db/migration
    password:
    baseline-on-migrate: true

datasource:
  url: jdbc:h2:mem:transactiondb;DB_CLOSE_DELAY=-1;
  driverClassName: org.h2.Driver
  username: sa
  password:
