name: Build and publish Docker images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push account-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./account-service
          push: true
          tags: mahdad12/account-service:latest

      - name: Build and push transaction-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./transaction-service
          push: true
          tags: mahdad12/transaction-service:latest